### PR TITLE
solves a few issues:)

### PR DESCRIPTION
**Pull request by crazysmile11012**
adds shader support #3 
fixes camera #13

### CODE REVIEW

**Comment by crazysmile11012** [comment]
it is unstable atm

**Comment by Rodmatronic** [comment]
K

**Comment by Rodmatronic** [comment]
Hold on, ADDS SHADER SUPPORT?!?

**Comment by Rodmatronic** [comment]
Holy shit

**Comment by crazysmile11012** [comment]
yes? shaders are a basic thing required to make ANY game
particles? requires glsl shaders
any lighting? glsl shaders
they are a basic requirement for ANY engine

**Comment by crazysmile11012** [comment]
https://en.wikipedia.org/wiki/OpenGL_Shading_Language

**Pull request merged**
